server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://ep-bitter-firefly-ahzw2v8k-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_LYy8fqsiSo1g
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql.BasicBinder: trace

jwt:
  secret: LxvN2oVkP8xPjQ1b2jSx1uTt0p8HsO3W9Rg9ZTlEjYQ=
  expiration: 86400000